### ISSUE TITLE
why 'npm run start' with errors?

### ISSUE THREAD

**Issue by markqiu** [James-Ansley/latenights-textbook#1]
When I type npm run start, I got the following error in the browser:
```
This page crashed.
Hook useColorMode is called outside the <ColorModeProvider>. Please see https://docusaurus.io/docs/api/themes/configuration#use-color-mode.
```

**Comment by James-Ansley** [comment]
Hi,

Can you give me a few more details on this?
Are you using this repo unmodified? What version of docusaurus are you using? Can you provide some details regarding the page this error was thrown? etc.

**Comment by James-Ansley** [comment]
If you are setting up a new docusaurus instance you might find this useful as a starting point: https://github.com/James-Ansley/python-docusaurus-template

I made a template repository for docusaurus sites with runnable code examples.

**Comment by markqiu** [comment]
It works! Thank you very much!
